"""Regression coverage for Streamlit widget identities across callable pages.

Dashboard tests use softmax values generated by the real local checkpoint.
No probability fixtures or substitute inference results are constructed.
"""

from copy import deepcopy
from io import BytesIO
import os
import unittest
from unittest.mock import patch

from streamlit.testing.v1 import AppTest

from tests.test_ui import APP_FILE, _assert_clean, _navigate


def _replace_document_results():
    import streamlit as st
    from pages.document_analysis import _save_analysis, render_results

    if st.button("Buka analisis berikutnya", key="replace_test_document"):
        _save_analysis(st.session_state["next_payload"], {"name": "next-report.txt"})
    render_results()


class DraftNavigationRegressionTests(unittest.TestCase):
    def test_draft_survives_direct_navigation_between_pages_with_same_widget(self):
        draft = "Penggunaan energi terbarukan mencapai 30% pada tahun 2024."
        with patch("core.inference.predict_batch", side_effect=AssertionError("Unrequested inference")) as inference:
            app = AppTest.from_file(APP_FILE, default_timeout=30).run()
            app.text_area(key="quick_text_widget").set_value(draft).run()
            for title in ("Analisis Dokumen", "Uji Teks Cepat", "Beranda", "Tentang Model", "Uji Teks Cepat"):
                with self.subTest(page=title):
                    _navigate(app, title)
                    _assert_clean(self, app)
                    self.assertEqual(app.session_state["quick_draft"], draft)
                    if title != "Tentang Model":
                        self.assertEqual(app.text_area(key="quick_text_widget").value, draft)
            updated = draft + " Angka ini memerlukan verifikasi laporan sumber."
            app.text_area(key="quick_text_widget").set_value(updated).run()
            app.run()
            self.assertEqual(app.session_state["quick_draft"], updated)
            self.assertEqual(app.text_area(key="quick_text_widget").value, updated)
        inference.assert_not_called()

    def test_quick_model_load_failure_clears_ready_state(self):
        from core.model import ModelError

        app = AppTest.from_file(APP_FILE, default_timeout=30).run()
        self.assertIsNone(app.session_state["model_error"])
        app.session_state["model_ready"] = True
        app.text_area(key="quick_text_widget").set_value("Kami menjaga kelestarian lingkungan untuk generasi berikutnya.").run()
        message = "Checkpoint gagal dimuat dalam pengujian penanganan error."
        with patch("pages.quick_test.load_model", side_effect=ModelError(message)):
            app.button(key="analyze_quick").click().run()
        self.assertEqual(len(app.exception), 0)
        self.assertFalse(app.session_state["model_ready"])
        self.assertEqual(app.session_state["model_load_error"], message)
        self.assertTrue(any(message in error.value for error in app.error))

    def test_document_model_load_failure_clears_ready_state(self):
        from core.model import ModelError

        uploaded = BytesIO("Penggunaan energi terbarukan mencapai tiga puluh persen dari konsumsi energi.".encode("utf-8"))
        uploaded.name = "error-handling-test.txt"
        message = "Checkpoint gagal dimuat dalam pengujian dokumen."
        with patch("streamlit.file_uploader", return_value=uploaded):
            app = AppTest.from_file(APP_FILE, default_timeout=30).run()
            self.assertIsNone(app.session_state["model_error"])
            app.session_state["model_ready"] = True
            with patch("pages.document_analysis.load_model", side_effect=ModelError(message)):
                app.button(key="analyze_document").click().run()
        self.assertEqual(len(app.exception), 0)
        self.assertFalse(app.session_state["model_ready"])
        self.assertEqual(app.session_state["model_load_error"], message)
        self.assertTrue(any(message in error.value for error in app.error))


@unittest.skipUnless(
    os.getenv("BUTO_IJO_RUN_MODEL_TESTS") == "1",
    "Set BUTO_IJO_RUN_MODEL_TESTS=1 for UI tests with actual model probabilities.",
)
class DashboardNavigationRegressionTests(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        from core.inference import predict_batch
        from core.model import load_model
        from core.risk import calculate_document_risk
        from core.settings import get_settings

        settings = get_settings()
        bundle = load_model(settings.model_path)
        cls.results = predict_batch([
            {"claim_id": 1, "page": 1, "text": "Penggunaan energi terbarukan mencapai 30% dari total konsumsi energi perusahaan."},
            {"claim_id": 2, "page": 2, "text": "Kami berkomitmen mewujudkan masa depan yang lebih hijau untuk semua."},
        ], bundle=bundle, settings=settings)
        cls.summary = calculate_document_risk(cls.results)

    def _seed_results(self, app):
        app.session_state["original_probabilities"] = deepcopy(self.results)
        app.session_state["analysis_results"] = deepcopy(self.results)
        app.session_state["risk_summary"] = deepcopy(self.summary)
        app.session_state["document_metadata"] = {"name": "navigation-test.txt"}

    def test_failed_new_upload_still_identifies_results_as_previous_document(self):
        from io import BytesIO
        from tests.test_ui import _document_results

        app = AppTest.from_function(_document_results, default_timeout=30)
        self._seed_results(app)
        metadata = {"name": "previous-report.pdf", "signature": "previous-signature"}
        app.session_state["document_metadata"] = metadata
        app.session_state["_prepared_upload"] = {"metadata": dict(metadata)}
        broken_upload = BytesIO(b"This is not a valid PDF")
        broken_upload.name = "broken-report.pdf"
        app.session_state["document_file"] = broken_upload
        with patch("core.inference.predict_batch", side_effect=AssertionError("Unrequested inference")) as inference:
            app.run()
        _assert_clean(self, app)
        self.assertTrue(any("previous-report.pdf" in item.value for item in app.info))
        self.assertEqual(app.session_state["original_probabilities"], self.results)
        inference.assert_not_called()

    def test_threshold_survives_direct_navigation_and_results_are_consistent(self):
        from core.risk import calculate_document_risk

        app = AppTest.from_file(APP_FILE, default_timeout=30)
        self._seed_results(app)
        threshold = .77
        expected = calculate_document_risk(self.results, threshold=threshold)
        with patch("core.inference.predict_batch", side_effect=AssertionError("Unrequested inference")) as inference:
            app.run()
            app.slider(key="threshold_widget").set_value(threshold).run()
            for title in ("Analisis Dokumen", "Beranda", "Uji Teks Cepat", "Analisis Dokumen"):
                with self.subTest(page=title):
                    _navigate(app, title)
                    _assert_clean(self, app)
                    self.assertEqual(app.session_state["_analysis_threshold"], threshold)
                    self.assertEqual(app.session_state["original_probabilities"], self.results)
                    self.assertEqual(app.session_state["risk_summary"], expected)
                    if title != "Uji Teks Cepat":
                        self.assertEqual(app.slider(key="threshold_widget").value, threshold)
            app.slider(key="threshold_widget").set_value(.62).run()
            self.assertEqual(app.session_state["_analysis_threshold"], .62)
            self.assertEqual(app.session_state["risk_summary"], calculate_document_risk(self.results, threshold=.62))
        inference.assert_not_called()

    def test_new_analysis_resets_filters_from_previous_document(self):
        app = AppTest.from_function(_replace_document_results, default_timeout=30)
        self._seed_results(app)
        app.session_state["next_payload"] = {
            "results": deepcopy(self.results), "original_probabilities": deepcopy(self.results),
            "risk_summary": deepcopy(self.summary),
        }
        app.run()
        app.text_input(key="claim_search").set_value("a search that matches no claim").run()
        app.selectbox(key="claim_sort").set_value("Page").run()
        app.selectbox(key="claim_filter").set_value("Low Indication").run()
        self.assertTrue(any("Tidak ada klaim" in item.value for item in app.info))
        app.button(key="replace_test_document").click().run()
        _assert_clean(self, app)
        self.assertEqual(app.text_input(key="claim_search").value, "")
        self.assertEqual(app.selectbox(key="claim_filter").value, "Semua Klaim")
        self.assertEqual(app.selectbox(key="claim_sort").value, "Highest Risk")
        self.assertFalse(any("Tidak ada klaim" in item.value for item in app.info))
        self.assertEqual(app.session_state["document_metadata"]["name"], "next-report.txt")

    def test_successful_quick_retry_clears_previous_load_error(self):
        from core.model import ModelError

        app = AppTest.from_file(APP_FILE, default_timeout=30).run()
        app.text_area(key="quick_text_widget").set_value(self.results[0]["claim"]).run()
        with patch("pages.quick_test.load_model", side_effect=ModelError("Pengujian kegagalan sebelum retry.")):
            app.button(key="analyze_quick").click().run()
        self.assertFalse(app.session_state["model_ready"])
        app.button(key="analyze_quick").click().run()
        _assert_clean(self, app)
        self.assertTrue(app.session_state["model_ready"])
        self.assertNotIn("model_load_error", app.session_state)
        self.assertAlmostEqual(
            app.session_state["quick_result"]["greenwashing_probability"],
            self.results[0]["greenwashing_probability"], delta=1e-5,
        )


if __name__ == "__main__":
    unittest.main()
